---

- name: Install net-snmp
  yum: name={{ item }} state=present
  with_items:
    - net-snmp
    - net-snmp-utils

- name: Start snmptrapd
  service: name=snmptrapd state=started enabled=yes

- name: Install snmptrapd config
  template: src=snmptrapd.conf.j2 dest=/etc/snmp/snmptrapd.conf
  notify: restart snmptrapd

- name: Install snmptrapd options
  template: src=snmptrapd.j2 dest=/etc/sysconfig/snmptrapd
  notify: restart snmptrapd

- name: Add iptables rule
  lineinfile: dest=/etc/sysconfig/iptables state=present regexp="{{ item }}.*162"
    insertbefore="^-A INPUT -j REJECT --reject-with icmp-host-prohibited"
    line="-A INPUT -s {{ item }} -p tcp -m state --state NEW -m tcp --dport 162 -j ACCEPT"
  notify: restart iptables
  with_items: netequip_subnets

