---
- name: Install Mysql package
  yum: name=mysql-server state=present

# Red'd for the ansible mysql_db & mysql_user modules
- name: Install MySQL-python package
  yum: name=MySQL-python state=present

- name: Start Mysql Service
  service: name=mysqld state=started enabled=true

- name: Add iptables rule
  lineinfile: dest=/etc/sysconfig/iptables state=present regexp="3306"
    insertbefore="^-A INPUT -j REJECT --reject-with icmp-host-prohibited"
    line="-A INPUT -s {{ hostvars[groups['app-server'][0]]['ansible_eth1']['ipv4']['address'] }} -p tcp -m state --state NEW -m tcp --dport 3306 -j ACCEPT"
  notify: restart iptables

- name: Create NetManage database
  mysql_db: name={{ db_name }} state=present

- name: Create NetManage database user (local)
  mysql_user: name={{ db_user }} password={{ db_password }} priv={{ db_name}}.*:ALL
    host=127.0.0.1 state=present

- name: Create NetManage database user (remote)
  mysql_user: name={{ db_user }} password={{ db_password }} priv={{ db_name }}.*:ALL
    host='{{ hostvars[groups['db-server'][0]]['ansible_eth1']['ipv4']['address'] }}'
    state=present

#- name: Create NetManage database user
#  mysql_user: name={{ db_user }} password={{ db_password }} priv={{ db_name }}.*:ALL
#     host='{{ hostvars[groups['db-server'][0]]['ansible_hostname'] }}' state=present

