---

- name: Install EPEL repo
  yum: name=http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm state=present

- name: Install common packages
  yum: name={{ item }} state=present
  with_items:
    - curl
    - git

